jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Install JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Configure Gradle
      run: ./gradlew help
    - continue-on-error: true
      name: Spot check
      run: ./gradlew spotlessCheck --stacktrace
    - continue-on-error: true
      name: Build project
      run: ./gradlew assemble --stacktrace
    - continue-on-error: true
      name: Run tests
      run: ./gradlew test --stacktrace
    - continue-on-error: true
      name: Final checks
      run: ./gradlew check --stacktrace
    - continue-on-error: true
      env:
        SONATYPE_NEXUS_PASSWORD: ${{ secrets.SonatypePassword }}
        SONATYPE_NEXUS_USERNAME: ${{ secrets.SonatypeUsername }}
      if: success() && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        && matrix.java_version == '1.8'
      name: Upload snapshot (main only)
      run: ./gradlew uploadArchives
    strategy:
      matrix:
        java_version:
        - 1.8
        - 10
        - 11
        - 12
        - 13
        - 14
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
